import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Services from "../components/Services";
import Footer from "../components/Footer";
import Form from "../components/Form";
import NewNavbar from "../components/NewNavbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BUIDLR | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <NewNavbar />
      </header>

      <main>
        <Hero />
        <About />
        <Services />
        <Form />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
